# docker-compose.yml
version: '3'

services:

  flask:
    image: my_docker_flask:latest
    build:
      context: ./services/flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
  webapp:
    image: vuejs-cookbook/dockerize-vuejs-app
    build:
      context: ./services/vue
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - flask